### ISSUE TITLE
Continuous integration?

### ISSUE THREAD

**Issue by thbar** [thmsmlr/instructor_ex#14]
I have noticed that the tests are not run automatically while issuing a PR here:
- #13 

Would you be interested in some contribution around that, e.g. maybe running GitHub actions on top of each PR?

It could start easily, with just `mix test`, and later do more connected testing.

Happy to provide some help here if you fancy it.

**Comment by thmsmlr** [comment]
Yup, I definitely want to add CI. One difficult part about the tests is that there a bunch that actually query OpenAI, or use llamacpp. I don't really want to put my personal openai key to run against anyone's PR. So we'll have to disable those. which unfortunately means there will still be some amount of local verification required. But w/e something is better than nothing.

Okay all this being said, it's been awhile since i've setup Github Actions and probably never for Elixir.

Do you have a good template I can reference to set it up?

**Comment by thbar** [comment]
Ok! Yes, sure, there is no reason to use your personal credentials here. We can filter these out initially as well.

We can also create a specific account or ask for one for open-source project (maybe they provide that) for testing.

I will provide a starting point - I'm on holidays next week though, so hold on a bit (unless someone does it before :smile:)

**Comment by joshuataylor** [comment]
Depending on how many endpoints are requested..

How I've handled similar in the past is to use mocking for "known good responses", where you store the JSON response in a file (so you know what the data looks like), then use something like [bypass](https://hexdocs.pm/bypass/Bypass.html) the change the endpoint you're accessing.

I really like this approach, as coming back to the project you can check what you *think you should be receiving* vs what you actually are.

OpenAI and other endpoints are fairly stable, this is dealing with.. "less than ideal" APIs :).

**Comment by thbar** [comment]
I took a first stab at this in #28.
