### ISSUE TITLE
Runtime switching adapters?

### ISSUE THREAD

**Issue by cigrainger** [thmsmlr/instructor_ex#22]
Hey @thmsmlr! Just got to trying this out properly today. Really nice stuff. Locking things to a single adapter via config feels overly restrictive -- some folks use a combination of providers for different purposes. Would you be up for a PR that allows passing an adapter as an opt for `chat_completion` to override the configured adapter?

**Comment by thbar** [comment]
I would second that: it is really important to make the code as usable as possible, with e.g. multiple credentials for scalability or security reasons, and to allow multiple adapters fixed at runtime too.

While it is nice to have an easy opt-in via config, it is even greater to be able to modify adapters & credentials at runtime so that the library can cover many scénarios.

**Comment by thmsmlr** [comment]
I have doubts on the usecases, but there isn't any reason not to. Hell, even in the Python library you can patch multiple clients with different configurations.

In fact, half the reason why I removed the OpenAI.ex dependency is that some of it's configurations are global and not overridable.

Long story short, I'd be in support of this change and welcome any PR that achieves it. Seems like a small refactor

**Comment by thmsmlr** [comment]
Fixed by #23

**Comment by matthops** [comment]
> I would second that: it is really important to make the code as usable as possible, with e.g. multiple credentials for scalability or security reasons, and to allow multiple adapters fixed at runtime too.

@thmsmlr Really enjoyed exploring this tool so far, thanks for all your work on this. 

Had a quick question for you - with your fix here, it looks like the adapter can be updated at runtime, but as far as I can tell from looking through the code, credentials cannot be updated at runtime. Is that correct? 

If so, is that an intentional design decision or would that be an update you'd be open to considering? I'm somewhat new to Elixir, but I'd be happy to make an attempt at putting a PR together for that functionality. 

If that is actually possible and I just missed it, then I'd be happy to get the info on how to do that and put a PR together to update the docs and help clear things up for people like me. Thanks in advance!
